imports = [
  "language.go"
]

[[env]]
name = "DATABASE_URL"
value = "postgres://postgres:@127.0.0.1:5432/cicero?sslmode=disable"

[[env]]
name = "CICERO_WORKFLOW_SRC"
value = "."

[[env]]
name = "LOKI_ADDR"
value = "http://127.0.0.1:3100"

[[env]]
name = "PIP_PREFIX"
eval = "export PIP_PREFIX=$PWD/_build/pip_packages"

[[env]]
name = "PYTHONPATH"
eval = "export PYTHONPATH=$PWD/_build/pip_packages/lib/python3.9/site-packages:$PYTHONPATH"

[[env]]
name = "PATH"
eval = "export PATH=$PIP_PREFIX/bin:$PATH"

[[commands]]
package = "go"

[[commands]]
package = "dbmate"

[[commands]]
package = "golangci-lint"

[[commands]]
package = "liftbridge-cli"

[[commands]]
package = "liftbridge"

[[commands]]
package = "gouml"

[[commands]]
package = "nomad"

[[commands]]
package = "damon"

[[commands]]
name = "lint"
command = "golangci-lint run && gocritic check -enableAll ./... && fd -e nix -X nixfmt -c"
help = "Run code linters"

[[commands]]
package = "nomad-dev"
help = "Run Nomad in development mode with Nix driver"

[[commands]]
name = "psqlc"
command = "psql -d \"$DATABASE_URL\" \"$@\""
help = "psql into Cicero DB"

[[commands]]
name = "dev-run"
command = "cue export ./jobs -e jobs.dev | nomad run -"
help = "run postgres, loki, and liftbridge in nomad"

[[commands]]
name = "go-run"
command = "go run . start --web-listen=:8084"
help = "run this project"

[[commands]]
name = "all-run"
command = "dev-run ; dbmate up ; go run . start --web-listen=:8084"
help = "run all of this project"

[devshell]
name = "cicero"
packages = [
  "cicero-evaluator-nix",
  "cue",
  "diffutils",
  "fd",
  "gcc",
  "go",
  "gocode",
  "gocritic",
  "goimports",
  "gopls",
  "grafana-loki",
  "nixfmt",
  "nomad-follower",
  "postgresql_12",
  "sqliteInteractive",
  "vector",
  "python3",
  "python3Packages.pip",
  "python3Packages.requests",
]
